apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: speech.nandy.io
source:
  site: github.com
  repo: nandy-io/speech
---
apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: chore.nandy.io
source:
  site: github.com
  repo: nandy-io/chore