apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: klot-io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klot-io-api
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: ["klotioapps.klot.io"]
  resources: ["klotioapps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klot-io-api
subjects:
- kind: ServiceAccount
  name: api
  namespace: klot-io
roleRef:
  kind: ClusterRole
  name: klot-io-api
  apiGroup: rbac.authorization.k8s.io